//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Taken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Taken()
        {
            this.Fines = new HashSet<Fine>();
        }
    
        public int TakeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public Nullable<int> BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> TakenDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public byte[] Picture { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsReturned { get; set; }
    
        public virtual User User { get; set; }
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fine> Fines { get; set; }
    }
}
