//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Library_ManagementEntities : DbContext
    {
        public Library_ManagementEntities()
            : base("name=Library_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_Genre> Book_Genre { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Book_Taken> Book_Taken { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Fine> Fines { get; set; }
    
        public virtual ObjectResult<Validate_User_Result> Validate_User(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Validate_User_Result>("Validate_User", emailParameter, passwordParameter);
        }
    
        public virtual int GenerateFine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateFine");
        }
    }
}
